server:
  servlet:
    context-path: /card

spring:
  profiles:
    active: ${ENVIRONMENT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1   
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false

database:
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}